development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: srilinks
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: newsrilinks
  pool: 5
  timeout: 5000