# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8c383f29732e2079c4bf0ddcb334c72d63d8da29a3c312a77b3d90f41b76833f614aef51962d71b672c3d3c3ddac7e6fca7557ee43530c31bba4415e08de01

test:
  secret_key_base: e6859816c6fa4f5bdf1550663762c2680eaf28331c2a2ec899fca454bd3b515caa2dfc3c9d0d7ab4805f620e6333de507119e8262abde9932a06b1b2633363b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
